import dynamic from 'next/dynamic';
const ReactPlayer = dynamic(() => import('react-player/lazy'), { ssr: false });
import Head from 'next/head'
import React from 'react';
import Navigation from '@/components/navigation'
import { Box, Toolbar } from '@mui/material'


export default class Player extends React.Component {
    render() {
        var items = ['Video Stream', 'Labels'];
        var logos = ['movie', 'label'];
        var urls = ['/player', '/labels'];
        return (
            <>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box sx={{ display: 'flex' }}>
                <Navigation items={items} icons={logos} urls = {urls} />
                <Box component="div" sx={{ flexGrow: 1, p: 3 }}>
                    <Toolbar />
                    <p>Une jolie wordmap ?</p>
                </Box>
            </Box>
          </>
        )
    }
  }