import dynamic from 'next/dynamic';
const ReactPlayer = dynamic(() => import('react-player/lazy'), { ssr: false });
import Head from 'next/head'
import React from 'react';
import styles from '@/styles/Home.module.css'

export default class Player extends React.Component {
    render() {
        return (
            <>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <ReactPlayer id="coucou" url="/videos/1.mpd" controls/>
            </main>
          </>
        )
    }
  }